hello/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path 
from . import views 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("homeworks/", views.homework, name="homeworks"),
    path("homework/add", views.homeworkadd, name="homeworkadd"),
    path("homework/edit/<int:id>", views.homework_edit, name="homework_edit"),
    path("homework/delete/<int:id>", views.homework_delete, name="homework_delete"),
    path("homework/done/<int:id>", views.homework_done, name="homework_done")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class HomeWork(models.Model): 
    title = models.CharField(max_length=255, null=False)
    content = models.TextField(null=True, blank=True)
    deadline = models.DateField(null=True, blank=True)
    create_date = models.DateField(null=True, blank=True)
    created_user = models.ForeignKey( User, null=True, blank=True, on_delete=models.DO_NOTHING)
    done = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True, max_length=255, upload_to="uploads/")
    lesson = models.ForeignKey("Lesson",null=True, blank=True, on_delete=models.DO_NOTHING)
    
    
class Lesson(models.Model):
    name=models.CharField(max_length=120, null=True, blank=True)
    
    def __str__(self):
        return self.name

home/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import HomeWork


class NewUserForm(UserCreationForm):
    username = forms.CharField (
        label="username", 
        widget = forms.TextInput(attrs={
            "class": "form-control"
        }) 
    )
    password1 = forms.CharField( 
            label = "password", 
            widget=forms.PasswordInput(attrs={
                "class": "form-control"
            })
    )
    password2 = forms.CharField(
        label = "password",
        widget=forms.PasswordInput(attrs={
            "class": "form-control"
        })
    ) 
    
    
class LoginForm(AuthenticationForm):
    username = forms.CharField( 
        label="username",
        widget=forms.TextInput(attrs={
            "class": "form-control"  
        })
    )               
    password = forms.CharField(
        label="password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
        })
    )
    
    
class HomeWorkForm(forms.ModelForm):
    class Meta:
        model = HomeWork
        fields = ("title" , "content" , "deadline", "image", "lesson")
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
            "deadline": forms.DateInput(attrs={"class": "form-control", "type":"date"}),
            "image": forms.ClearableFileInput(),
            "lesson": forms.Select(attrs={"class": "form-control"})
        }

home/views.py
# home/wievs.py



import datetime
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import HomeWork
from .forms import NewUserForm
from .forms import LoginForm , HomeWorkForm
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator


def index(request):
    form = LoginForm()
    message = ""
    user = request.user
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                message = "login succes"
            else:
                message = "Invalid username or password"
        else:
            message = "Invalid username or password"
    return render(request, "home.html", {"form": form, "message": message, "user": user})


def register(request):
    form = NewUserForm()
    message = ""
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            message = "Register successful"
    return render(request, "register.html", {"form": form, "message": message})

def homework(request):
    home_works = HomeWork.objects.filter(created_user=request.user).order_by("id")
    paginator = Paginator(home_works, 2)
    page_number = request.GET.get("page")
    homework_page = paginator.get_page(page_number)
    return render(request, "homeworks.html", {"homeworks": homework_page,})  

def homeworkadd(request):
    form = HomeWorkForm()
    message = ""
    if request.method == "POST":
        form = HomeWorkForm(request.POST, request.FILES)
        if form.is_valid():
            homework = form.save(commit=False)
            homework.created_user = request.user
            homework.create_date = datetime.datetime.now()
            homework.save()
            message = "homework created successfully"
    return render(request, "homeworkadd.html", {'form': form, 'message': message})

def logout_view(request):
    logout(request)
    return redirect("index")


def homework_edit(request, id):
    homework=HomeWork.objects.get(id=id)
    form = HomeWorkForm(instance=homework)
    message = ''
    
    if request.method == "POST":
        print(request.FILES)
        form = HomeWorkForm(instance=homework,data=request.POST, files = request.FILES)
        if form.is_valid():
            form.save()
            message = "Homework Successfully edited"
    return render(request, 'homeworkadd.html', { "form":form, "message":message})


def homework_delete(request, id):
    homework = HomeWork.objects.get(id=id)
    homework.delete()
    return redirect("homeworks")

def homework_done(request, id):
    done = request.GET.get("done", False)
    homework = HomeWork.objects.get(id=id)
    homework.done = done
    homework.save()
    return redirect("homeworks")

hello/templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Homework to do</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    </head>
    <style></style>
    <body>
        <div vlass ="container">
            <ul class="nav bg-info">
                <li class="nav-item">
                    <a class="nav-link link-dark "href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-dark" href="/register">Register</a>
                </li>
                {% if user is not None and user.is_anonymous == False %}
                <li class="nav-item">
                    <a class="nav-link link-dark" href="/homeworks">home works</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-dark" href="/homework/add">Add homework</a>
                </li>
                {% endif %}
            </ul>
        <div>

       {% block content%}
       {% endblock%}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    </body>
</html>

hello/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-xl-5 col-lg-6 col-md-10 col-sm-12 mx-auto mt-5">
        {% if user is None or user.is_anonymous == True%}
        {% if message != "" %}
            <p class="alert alert-danger"> {{ message }} </p>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="id_username">Hereglegchiin ner</label>
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>
                <div class="form-group">
                    <label for="id_password">nuuts ug</label>
                    {{ form.password }}
                    {{ form.password.errors }}
                </div>
                <div class="text-center">
                    <br><button type="submit" class="btn btn-primary">Nevtreh</button>
                    
                </div>
            </div>
        </form>
        {% else %}
            Welcome {{ user.username }}.
            <a href="{%url 'logout'%}">log out</a>
        {% endif %}
    </div>
</div>
{% endblock %}

hello/templates/homeworkadd.html
{% extends "base.html"%}
{% block content %}
<div class="row">
    <div class="col-xl-5 col-ig-6 col-md-10 col-sm-12 mx-auto mt-5">
        <h2>Add homework</h2>
        {% if message != "" %}
            <p class="alert alert-success">{{message}}</p>
        {% endif %}
        <form method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="id_title">hicheel</label>
                        {{ form.title }}
                        {{ form.title.errors }}
                </div>
                <div class="form-group">
                    <label for="id_content">aguulga</label>
                        {{ form.content }}
                        {{ form.content.errors }}
                </div>
                <div class="form-group">
                    <label for="id_deadline">Duusah hugatsaa</label>
                            {{ form.deadline }}
                            {{ form.deadline.errors }}
                </div>
                <div class="form-group">
                    <label for="id_image">zurag</label>
                    {{ form.image }}
                    {{ form.image.errors }}
                </div>
                <div class="form-group">
                    <label for="id_lesson">hicheel songoh2</label>
                    {{ form.lesson }}
                    {{ form.lesson.errors }}
                </div>
                <div class="text-center">
                    <br><button type="submit" class="btn btn-primary">Geriin daalgavar burtgeh</button>
                </div> 
            </div>
        </form>
    </div>
</div>    
{% endblock %} 

hello/templates/homeworks.html
{% extends "base.html"%}
{% block content %}
<div class="row">
    <div class="col-mid-12 col-sm-12"></div>
    <h2>My Homeworks</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">hicheel</th>
                <th scope="col">aguulga</th>
                <th scope="col">duusah hugatsa</th>
                <th scope="col">nemsen ognoo</th>
                <th scope="col>">Zurag</th>
                <th scope="col">uildel</th>
            </tr>
            </thead>
            <tbody>
                {% for homework in homeworks %}
            <tr>
                <td><input type="checkbox" {% if homework.done == True %}checked{% endif %}
                    onclick="done(this, '{% url 'homework_done' homework.id %}')"
                    /></td>
                <td>{{ homework.title }}</td>
                <td>{{ homework.content }}</td>
                <td>{{ homework.deadline }}</td>
                <td>{{ homework.create_date }}</td>
                <td>
                    <img width="300" src="{{MEDIA_URL}}{{homework.image}}"</td>
                <td><a href="{% url "homework_edit" homework.id %}"> zasah</a>
                <a href="{% url "homework_delete" homework.id %}" 
                onclick="return confirm('ta ustgahdaa itgeltei baina uu?')">ustgah</a></td>
            </tr>
            {% endfor %}
        </body>
    </table>
    <!-- Paginaton -->
        <div class="paginaton">
            <span class="step-links">
                {% if homeworks.has_previous %}
                    <a href="?page=1">first</a>
                    <a href="?page={{ homeworks.previous_page_number }}">
                        previous 
                    </a>
                {% endif %}
            <span class="current">
               Page {{ homework.number }} of {{ homeworks.paginator.num_pages }}
            </span>
            {% if homeworks.has_next %}
                    <a href="?page={{ homeworks.next_page_number}}">next</a>
                    <a href="?page={{ homeworks.paginator.num_pages}}">
                last
                    <a/>
            {% endif %}
            </span>
        </div>
    </div>
</div>
<script>
    function done(target, url){
        if (target.checked == true){
            window.location = url + "?done=True"
        }else{
            window.location = url + "?done=False"
        }
    }
</script>

{% endblock %}

hello/templates/register.html
{% extends "base.html"%}
{% block content %}
<div class="row">
    <div class="col-xl-5 col-lg-6 col-md-10 col-sm-12 mx-auto mt-5">
        <h2>burtguuleh</h2>
        {% if message != "" %}
            <p class="alert alert-succes">{{ message }}</p>
        {% endif %}
        
        <form method="POST">
        {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="id_username">Hereglegchiin ner</label>
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>
                <div class="form-group">
                    <label for="id_password">nuuts ug</label>
                    {{ form.password1 }}
                    {{ form.password1.errors}}
                </div>
                <div class="form-group">
                    <label for="id_password">nuuts ug davtan oruulna uu</label>
                    {{ form.password2 }}
                    {{ form.password2.errors}}
                </div>
                <div class="text-center">
                    <br><button type="submit" class="btn btn-info">Burtguuleh</button>

                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}